# Generated by Django 4.2 on 2023-04-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_ordereditem_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_cost',
        ),
    ]
